name: pisco
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - netcdf4
  - cfgrib
  - pydap
  - scipy
  - bottleneck
  - distributed
  - matplotlib
  - cartopy
  - descartes
  - geopandas
  - shapely
  - rasterio
  - seaborn
  - tqdm
  - pandas-profiling
  - jupyterlab
  - nodejs
  - spyder
  - scikit-learn
  - scikit-image
  - intake
  - intake-xarray=0.3.1
  - gcsfs
  - python-graphviz
  - graphviz
  - pip
  - pip:
      - salem